"""
SFT 指令数据集 —— 自己构造的英文问答对

说明：
- 用贴近 WikiText-2（百科类）内容的简单英文问答，让 17M 小模型"接得住"
- 目标是演示 SFT 能让模型从"自由续写"变成"按问答格式回答"
- 数据格式：{"instruction": "...", "response": "..."}

运行：python src/make_sft_data.py
"""

import json
import os

# 100 条百科类英文问答对
SFT_DATA = [
    # --- 地理 (15) ---
    {"instruction": "What is the capital of France?",
     "response": "The capital of France is Paris."},
    {"instruction": "What is the capital of Japan?",
     "response": "The capital of Japan is Tokyo."},
    {"instruction": "What is the capital of Australia?",
     "response": "The capital of Australia is Canberra."},
    {"instruction": "What is the capital of Canada?",
     "response": "The capital of Canada is Ottawa."},
    {"instruction": "What is the capital of Brazil?",
     "response": "The capital of Brazil is Brasilia."},
    {"instruction": "What is the capital of Italy?",
     "response": "The capital of Italy is Rome."},
    {"instruction": "What is the largest ocean on Earth?",
     "response": "The largest ocean on Earth is the Pacific Ocean."},
    {"instruction": "Which continent is the largest by area?",
     "response": "Asia is the largest continent by area."},
    {"instruction": "What is the longest river in the world?",
     "response": "The Nile is often considered the longest river in the world."},
    {"instruction": "Where is the Sahara Desert located?",
     "response": "The Sahara Desert is located in northern Africa."},
    {"instruction": "What is the largest country by area?",
     "response": "Russia is the largest country by area."},
    {"instruction": "What is the smallest country in the world?",
     "response": "Vatican City is the smallest country in the world."},
    {"instruction": "Which mountain range separates Europe from Asia?",
     "response": "The Ural Mountains separate Europe from Asia."},
    {"instruction": "What is the highest mountain in Africa?",
     "response": "Mount Kilimanjaro is the highest mountain in Africa."},
    {"instruction": "Which country is known as the Land of the Rising Sun?",
     "response": "Japan is known as the Land of the Rising Sun."},
    # --- 历史 (15) ---
    {"instruction": "In which year did World War II end?",
     "response": "World War II ended in 1945."},
    {"instruction": "In which year did World War I begin?",
     "response": "World War I began in 1914."},
    {"instruction": "Who was the first president of the United States?",
     "response": "George Washington was the first president of the United States."},
    {"instruction": "What ancient civilization built the pyramids of Egypt?",
     "response": "The ancient Egyptians built the pyramids of Egypt."},
    {"instruction": "When did the French Revolution begin?",
     "response": "The French Revolution began in 1789."},
    {"instruction": "Who wrote the Declaration of Independence?",
     "response": "Thomas Jefferson was the principal author of the Declaration of Independence."},
    {"instruction": "What was the Roman Empire known for?",
     "response": "The Roman Empire was known for its military power, law, and engineering."},
    {"instruction": "Who discovered America in 1492?",
     "response": "Christopher Columbus reached the Americas in 1492."},
    {"instruction": "When did the United States declare independence?",
     "response": "The United States declared independence in 1776."},
    {"instruction": "Who was the leader of Nazi Germany during World War II?",
     "response": "Adolf Hitler was the leader of Nazi Germany."},
    {"instruction": "What was the Renaissance?",
     "response": "The Renaissance was a period of cultural and artistic revival in Europe."},
    {"instruction": "Which empire built the Great Wall of China?",
     "response": "The Chinese empires built the Great Wall over many centuries."},
    {"instruction": "When was the Roman Empire founded?",
     "response": "The Roman Empire was founded in 27 BC."},
    {"instruction": "What was the Industrial Revolution?",
     "response": "The Industrial Revolution was a period of rapid industrial growth beginning in the 18th century."},
    {"instruction": "Who was the famous queen of ancient Egypt?",
     "response": "Cleopatra was a famous queen of ancient Egypt."},
    # --- 科学 (18) ---
    {"instruction": "What is the chemical symbol for water?",
     "response": "The chemical symbol for water is H2O."},
    {"instruction": "What planet is known as the Red Planet?",
     "response": "Mars is known as the Red Planet."},
    {"instruction": "What force keeps planets in orbit around the sun?",
     "response": "Gravity keeps planets in orbit around the sun."},
    {"instruction": "What is the speed of light?",
     "response": "The speed of light is about 299,792 kilometers per second."},
    {"instruction": "What is the largest planet in our solar system?",
     "response": "Jupiter is the largest planet in our solar system."},
    {"instruction": "What gas do plants absorb from the atmosphere?",
     "response": "Plants absorb carbon dioxide from the atmosphere."},
    {"instruction": "What is the closest planet to the sun?",
     "response": "Mercury is the closest planet to the sun."},
    {"instruction": "What is the chemical symbol for gold?",
     "response": "The chemical symbol for gold is Au."},
    {"instruction": "What is the chemical symbol for oxygen?",
     "response": "The chemical symbol for oxygen is O."},
    {"instruction": "How many planets are in our solar system?",
     "response": "There are eight planets in our solar system."},
    {"instruction": "What is the study of earthquakes called?",
     "response": "The study of earthquakes is called seismology."},
    {"instruction": "What is the most abundant gas in the atmosphere?",
     "response": "Nitrogen is the most abundant gas in the atmosphere."},
    {"instruction": "What is the unit of electric current?",
     "response": "The unit of electric current is the ampere."},
    {"instruction": "What is the center of an atom called?",
     "response": "The center of an atom is called the nucleus."},
    {"instruction": "What is the fastest planet in our solar system?",
     "response": "Mercury is the fastest planet in our solar system."},
    {"instruction": "What causes the seasons on Earth?",
     "response": "The tilt of the Earth's axis causes the seasons."},
    {"instruction": "What is the main source of energy for the Earth?",
     "response": "The sun is the main source of energy for the Earth."},
    {"instruction": "What is the density of water?",
     "response": "The density of water is about one gram per cubic centimeter."},
    # --- 生物 (15) ---
    {"instruction": "What is the largest mammal in the world?",
     "response": "The blue whale is the largest mammal in the world."},
    {"instruction": "How many legs does an insect have?",
     "response": "Insects have six legs."},
    {"instruction": "What is the fastest land animal?",
     "response": "The cheetah is the fastest land animal."},
    {"instruction": "What do bees collect from flowers?",
     "response": "Bees collect nectar and pollen from flowers."},
    {"instruction": "What is the process by which plants make food?",
     "response": "The process is called photosynthesis."},
    {"instruction": "How many bones are in the adult human body?",
     "response": "The adult human body has 206 bones."},
    {"instruction": "What is the largest organ of the human body?",
     "response": "The skin is the largest organ of the human body."},
    {"instruction": "What is the tallest animal in the world?",
     "response": "The giraffe is the tallest animal in the world."},
    {"instruction": "What do we call animals that only eat plants?",
     "response": "Animals that only eat plants are called herbivores."},
    {"instruction": "What is the largest bird in the world?",
     "response": "The ostrich is the largest bird in the world."},
    {"instruction": "How many hearts does an octopus have?",
     "response": "An octopus has three hearts."},
    {"instruction": "What is the basic unit of life?",
     "response": "The cell is the basic unit of life."},
    {"instruction": "What do plants need to perform photosynthesis?",
     "response": "Plants need sunlight, water, and carbon dioxide for photosynthesis."},
    {"instruction": "What is the fastest fish in the ocean?",
     "response": "The sailfish is one of the fastest fish in the ocean."},
    {"instruction": "What is the study of living things called?",
     "response": "The study of living things is called biology."},
    # --- 艺术/文学 (12) ---
    {"instruction": "Who wrote the play Romeo and Juliet?",
     "response": "William Shakespeare wrote the play Romeo and Juliet."},
    {"instruction": "Who painted the Mona Lisa?",
     "response": "Leonardo da Vinci painted the Mona Lisa."},
    {"instruction": "What is the famous sculpture by Michelangelo?",
     "response": "David is a famous sculpture by Michelangelo."},
    {"instruction": "Who wrote the novel Moby Dick?",
     "response": "Herman Melville wrote the novel Moby Dick."},
    {"instruction": "Who wrote the play Hamlet?",
     "response": "William Shakespeare wrote the play Hamlet."},
    {"instruction": "Who painted the Starry Night?",
     "response": "Vincent van Gogh painted the Starry Night."},
    {"instruction": "Who wrote the novel Pride and Prejudice?",
     "response": "Jane Austen wrote the novel Pride and Prejudice."},
    {"instruction": "Who sculpted the statue of David?",
     "response": "Michelangelo sculpted the statue of David."},
    {"instruction": "Who wrote the Divine Comedy?",
     "response": "Dante Alighieri wrote the Divine Comedy."},
    {"instruction": "Who painted the Sistine Chapel ceiling?",
     "response": "Michelangelo painted the Sistine Chapel ceiling."},
    {"instruction": "Who wrote the novel War and Peace?",
     "response": "Leo Tolstoy wrote the novel War and Peace."},
    {"instruction": "What is the oldest surviving epic poem?",
     "response": "The Epic of Gilgamesh is one of the oldest surviving epic poems."},
    # --- 数学/物理 (10) ---
    {"instruction": "What is the value of pi?",
     "response": "Pi is approximately 3.14159."},
    {"instruction": "What is the square of 12?",
     "response": "The square of 12 is 144."},
    {"instruction": "Who developed the theory of relativity?",
     "response": "Albert Einstein developed the theory of relativity."},
    {"instruction": "What is the formula for the area of a circle?",
     "response": "The area of a circle is pi times the radius squared."},
    {"instruction": "What is the square root of 81?",
     "response": "The square root of 81 is 9."},
    {"instruction": "What is 7 times 8?",
     "response": "Seven times eight is 56."},
    {"instruction": "Who formulated the laws of motion?",
     "response": "Isaac Newton formulated the laws of motion."},
    {"instruction": "What is the circumference formula of a circle?",
     "response": "The circumference of a circle is 2 times pi times the radius."},
    {"instruction": "What is the value of the number e?",
     "response": "The number e is approximately 2.718."},
    {"instruction": "What is the formula for energy in physics?",
     "response": "The formula for energy is E equals m times c squared."},
    # --- 常识 (15) ---
    {"instruction": "How many continents are there on Earth?",
     "response": "There are seven continents on Earth."},
    {"instruction": "What is the smallest unit of life?",
     "response": "The cell is the smallest unit of life."},
    {"instruction": "What is the currency of the United Kingdom?",
     "response": "The currency of the United Kingdom is the pound sterling."},
    {"instruction": "What is the tallest mountain in the world?",
     "response": "Mount Everest is the tallest mountain in the world."},
    {"instruction": "What is the name of our galaxy?",
     "response": "Our galaxy is called the Milky Way."},
    {"instruction": "What is the boiling point of water?",
     "response": "The boiling point of water is 100 degrees Celsius."},
    {"instruction": "What is the study of stars and planets called?",
     "response": "The study of stars and planets is called astronomy."},
    {"instruction": "How many days are in a leap year?",
     "response": "A leap year has 366 days."},
    {"instruction": "What is the largest desert in the world?",
     "response": "The Antarctic Desert is the largest desert in the world."},
    {"instruction": "What is the freezing point of water?",
     "response": "The freezing point of water is 0 degrees Celsius."},
    {"instruction": "What is the fastest way to travel long distances?",
     "response": "Airplanes are the fastest way to travel long distances."},
    {"instruction": "How many players are on a soccer team?",
     "response": "A soccer team has eleven players on the field."},
    {"instruction": "What is the most spoken language in the world?",
     "response": "Mandarin Chinese is the most spoken language in the world."},
    {"instruction": "What is the largest island in the world?",
     "response": "Greenland is the largest island in the world."},
    {"instruction": "What color do you get by mixing red and blue?",
     "response": "Mixing red and blue gives purple."},
]


def format_sft_example(ex):
    """把一条问答对格式化成训练文本（GPT-2 风格指令格式）"""
    return (f"Question: {ex['instruction']}\n"
            f"Answer: {ex['response']}")


def main():
    data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
    os.makedirs(data_dir, exist_ok=True)
    out_path = os.path.join(data_dir, "sft_data.json")

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(SFT_DATA, f, ensure_ascii=False, indent=2)

    print(f"已生成 {len(SFT_DATA)} 条 SFT 指令数据 → {out_path}")
    print("\n格式示例：")
    print(format_sft_example(SFT_DATA[0]))


if __name__ == "__main__":
    main()
